  
//√÷≤πƒ⁄÷√±‰¡ø
//      vec4  nfx_FrontMaterial.emission
//      vec4  nfx_FrontMaterial.ambient
//      vec4  nfx_FrontMaterial.diffuse
//      vec4  nfx_FrontMaterial.specular
//      float nfx_FrontMaterial.shininess

"struct Material\n"
"{\n"
"   vec4 emission;\n"
"   vec4 ambient;\n"
"   vec4 diffuse;\n"
"   vec4 specular;\n"
"   float shininess;\n"
"};\n"
"uniform Material nfx_FrontMaterial;\n"
